### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by samreetdhillon**

### CODE REVIEW

**Review by ravgeetdhillon — COMMENTED** [review]
LGTM

**Review by samreetdhillon — COMMENTED** [review]
Woow

**Review by ravgeetdhillon — APPROVED** [review]
LGTM

**Review by ravgeetdhillon — APPROVED** [review]
LGTM

**Comment by samreetdhillon** [comment]
Because this request is over your head, so you better have github if you
gonna pull up

**Pull request merged**
